package jobs

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"time"
)

// Status values a job can be in. running is the only one that means "still
// going"; orphaned is the honest answer when a supervisor died without ever
// writing an outcome.
const (
	StatusRunning  = "running"
	StatusSuccess  = "success"
	StatusPartial  = "partial"
	StatusFailed   = "failed"
	StatusAborted  = "aborted"
	StatusOrphaned = "orphaned"
)

// ProfileRun is one profile inside a job. A run started from a tag contains
// several of them and they are executed in sequence, exactly as the in-window
// runner always did.
type ProfileRun struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Sources      []string `json:"sources"`
	Destinations []string `json:"destinations"`
	// Options carries the profile's rsync options, opaque to this package: the
	// caller owns their shape and this file only ferries them to the
	// supervisor. Deliberately not a stored command line — a state file is
	// something the app later reads back and acts on, and rebuilding the
	// arguments from structured options keeps a tampered file from turning
	// into a way to run something else.
	Options json.RawMessage `json:"options,omitempty"`
}

// State is what a job leaves on disk. It is small on purpose: it survives the
// log (which gets deleted, see Store.Cleanup) and is what the window shows
// when the log is long gone.
type State struct {
	JobID string `json:"jobId"`
	// Label is what the window shows: a profile name, or "Tag: serale".
	Label      string       `json:"label"`
	Profiles   []ProfileRun `json:"profiles"`
	Status     string       `json:"status"`
	PID        int          `json:"pid"`
	StartedAt  time.Time    `json:"startedAt"`
	FinishedAt time.Time    `json:"finishedAt,omitempty"`
	ExitCode   int          `json:"exitCode"`
	// CurrentProfile and CurrentDest say where the job has got to, so the
	// window can show progress without parsing the log.
	CurrentProfile string `json:"currentProfile,omitempty"`
	CurrentDest    string `json:"currentDest,omitempty"`
	LogTruncated   bool   `json:"logTruncated"`
	// Summary outlives the log: a job that went fine has its log deleted, and
	// this one line is all that remains of it.
	Summary string   `json:"summary,omitempty"`
	Issues  []string `json:"issues,omitempty"`
}

// Running reports whether the state claims to be in progress. Whether it
// really is can only be answered by the lock — see Store.IsAlive.
func (s State) Running() bool { return s.Status == StatusRunning }

// AllDestinations lists every destination the job writes to. Should this ever
// grow a parallel mode, this is what lets a scheduler refuse two jobs aimed at
// the same place: overlapping destinations, not clashing filenames, is the
// real hazard there.
func (s State) AllDestinations() []string {
	seen := map[string]bool{}
	var out []string
	for _, p := range s.Profiles {
		for _, d := range p.Destinations {
			if !seen[d] {
				seen[d] = true
				out = append(out, d)
			}
		}
	}
	return out
}

// jobIDPattern is what a job id is allowed to look like. Every path in this
// package is built from an id, so an id that could contain "/" or ".." would
// be a way to make the app read — or delete — arbitrary files. Ids are
// generated by NewJobID, but they also arrive from disk, where a corrupted or
// tampered file could carry anything.
var jobIDPattern = regexp.MustCompile(`^[0-9a-f]{32}$`)

// NewJobID returns an id for one execution. It is per run, not per profile: a
// profile is started many times and each run owns its own files.
func NewJobID() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		// crypto/rand failing is not survivable in any meaningful way; fall
		// back to the clock so a backup can still be started.
		return hex.EncodeToString([]byte(fmt.Sprintf("%016x", time.Now().UnixNano())))
	}
	return hex.EncodeToString(b)
}

// ValidJobID guards every path built from an id.
func ValidJobID(id string) bool { return jobIDPattern.MatchString(id) }

// Paths gathers the files belonging to one job. They are always derived from
// the id and the current directory, never read from a stored field: a stored
// absolute path breaks as soon as the config directory moves, and a tampered
// one would point the app (and its cleanup, which deletes files) anywhere on
// disk.
type Paths struct {
	State string
	Log   string
	Lock  string
}

// PathsFor builds the file names for a job id, or an error if the id is not
// one this package could have produced.
func PathsFor(dir, jobID string) (Paths, error) {
	if !ValidJobID(jobID) {
		return Paths{}, fmt.Errorf("job id non valido: %q", jobID)
	}
	return Paths{
		State: filepath.Join(dir, jobID+".json"),
		Log:   filepath.Join(dir, jobID+".log"),
		Lock:  filepath.Join(dir, jobID+".lock"),
	}, nil
}

// WriteState saves the state under its own job id.
func WriteState(dir string, s State) error {
	return WriteStateAt(dir, s.JobID, s)
}

// WriteStateAt saves the state atomically under an explicit job id: a
// temporary file plus a rename, so a window reading the directory never
// catches a half-written JSON. The window polls these files while a job runs,
// so that is not a theoretical race.
func WriteStateAt(dir, jobID string, s State) error {
	p, err := PathsFor(dir, jobID)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	tmp := p.State + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, p.State)
}

// ReadState loads one job's state.
func ReadState(dir, jobID string) (State, error) {
	p, err := PathsFor(dir, jobID)
	if err != nil {
		return State{}, err
	}
	data, err := os.ReadFile(p.State)
	if err != nil {
		return State{}, err
	}
	var s State
	if err := json.Unmarshal(data, &s); err != nil {
		return State{}, err
	}
	// Trust the filename, not the contents: the id in the file could disagree
	// with the file it lives in, and every path is built from the id.
	s.JobID = jobID
	return s, nil
}
